spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/logistics_dashboards?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USER:logistics}
spring.datasource.password=${DB_PASSWORD:logistics}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.flyway.locations=classpath:db/migration
